If assets is created then move to nextstep

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,13 +24,20 @@ jobs:
       - name: Build project
         run: npm run build
 
-        # just bot config
+      # if assets is created
+      - name: List dist folder
+        run: ls -R dist
+
       - name: Commit and Push dist/assets
         run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add dist/assets  # Stage the 'dist/assets' folder
-          git commit -m "CI: Update build assets [skip ci]"
-          git push origin main  # Push the changes to the 'main' branch
+          if [ -d dist/assets ]; then
+            git config --global user.name "github-actions[bot]"
+            git config --global user.email "github-actions[bot]@users.noreply.github.com"
+            git add dist/assets
+            git commit -m "CI: Update build assets [skip ci]"
+            git push origin main
+          else
+            echo "dist/assets folder not found"
+            exit 1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
